from fastapi import FastAPI, Header, WebSocket, WebSocketException, WebSocketDisconnect, HTTPException
from contextlib import asynccontextmanager
from pathlib import Path
from dataclasses import dataclass
import uuid
import uvicorn
import asyncio
import logging
from ground_station_v2.telemetry_timeline import TelemetryTimelineQueue, TelemetryTimelineWorker
from ground_station_v2.replay import Replay
from ground_station_v2.ingestion import ingest_global_radio_packets, ingest_global_replay_packets, ingest_client_replay_packets, recorder

logger = logging.getLogger(__name__)

@dataclass
class ClientReplayState:
    instance: Replay
    ingest_task: asyncio.Task[None]
    
    async def cleanup(self):
        """Cancel and await ingest task"""
        self.ingest_task.cancel()
        try:
            await self.ingest_task
        except asyncio.CancelledError:
            pass

@dataclass
class ClientState:
    websocket: WebSocket
    mode: str
    replay: ClientReplayState | None = None

connected_clients: dict[str, ClientState] = {}
live_queue: TelemetryTimelineQueue = TelemetryTimelineQueue()
_from_recording: Path | None = None

def get_live_clients():
    return {client_id: state.websocket for client_id, state in connected_clients.items() if state.mode == "live"}

async def get_client_state(x_client_id: str = Header(alias="X-Client-ID")) -> ClientState:
    """FastAPI dependency to validate and retrieve client state"""
    if x_client_id not in connected_clients:
        raise HTTPException(status_code=401, detail="Client not connected")
    return connected_clients[x_client_id]

async def start_client_replay(client_id: str, state: ClientState, replay_path: str, speed: float) -> ClientReplayState:
    """Setup and start a client replay session"""
    replay_instance = Replay()
    replay_instance.start(replay_path, speed)
    ingest_task = asyncio.create_task(ingest_client_replay_packets(replay_instance, state.websocket))
    
    return ClientReplayState(
        instance=replay_instance,
        ingest_task=ingest_task
    )

@asynccontextmanager
async def lifespan(app: FastAPI):
    live_worker = TelemetryTimelineWorker(live_queue, get_live_clients)
    asyncio.create_task(live_worker.run())
    
    if _from_recording is None:
        asyncio.create_task(ingest_global_radio_packets(live_queue))
    else:
        asyncio.create_task(ingest_global_replay_packets(live_queue, _from_recording))
        logger.info(f"Started global replay ingestion from: {_from_recording}")
    
    yield


app = FastAPI(lifespan=lifespan)


# all the requests below expect the X-Client-ID header to be set with the client_id from the request above
# for now it's not checked whether it was generated by the get_client_id endpoint or not, this will be changed

# TODO: include the header id check in middleware

@app.post("/replay_play")
async def replay_play(
    replay_path: str,
    speed: float = 1.0,
    x_client_id: str = Header(alias="X-Client-ID")
):
    state = await get_client_state(x_client_id)

    try:
        if state.replay:
            await state.replay.cleanup()
        
        state.mode = "replay"
        state.replay = await start_client_replay(x_client_id, state, replay_path, speed)
        
        logger.info(f"Replay started for client {x_client_id}: {replay_path} at {speed}x")
        return {"status": "ok", "replay_path": replay_path, "speed": speed}
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error(f"Error starting replay: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to start replay: {str(e)}")


@app.post("/resume_live")
async def resume_live(x_client_id: str = Header(alias="X-Client-ID")):
    state = await get_client_state(x_client_id)
    
    if state.replay:
        await state.replay.cleanup()
    
    state.mode = "live"
    state.replay = None
    
    logger.info(f"Client {x_client_id} resumed live mode")
    return {"status": "ok"}


@app.post("/replay_pause")
async def replay_pause(
    paused: bool = True,
    speed: float = 1.0,
    x_client_id: str = Header(alias="X-Client-ID")
):
    state = await get_client_state(x_client_id)
    if not state.replay or not state.replay.instance.is_playing():
        raise HTTPException(status_code=400, detail="No replay is currently active")

    if paused:
        state.replay.instance.pause()
        logger.info(f"Replay paused for client {x_client_id}")
    else:
        state.replay.instance.resume(speed)
        logger.info(f"Replay resumed for client {x_client_id} at {speed}x")

    return {"status": "ok", "paused": paused}


@app.post("/replay_stop")
async def replay_stop(x_client_id: str = Header(alias="X-Client-ID")):
    state = await get_client_state(x_client_id)
    
    if state.replay and state.replay.instance.is_playing():
        state.replay.instance.stop()
        await state.replay.cleanup()
        logger.info(f"Replay stopped for client {x_client_id}")
    
    return {"status": "ok"}


@app.post("/record_start")
async def record_start(x_client_id: str = Header(alias="X-Client-ID")):
    recorder.start()
    logger.info(f"Record start for client {x_client_id}")
    return {"status": "ok"}


@app.post("/record_stop")
async def record_stop(x_client_id: str = Header(alias="X-Client-ID")):
    recorder.stop()
    logger.info(f"Record stop for client {x_client_id}")
    return {"status": "ok"}


@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket, x_client_id: str = Header(alias="X-Client-ID")):
    if x_client_id in connected_clients:
        logger.warning(f"Client already connected: {x_client_id}")
        raise WebSocketException(code=1008, reason="Client already connected")

    await websocket.accept()
    
    state = ClientState(
        websocket=websocket,
        mode="live"
    )
    connected_clients[x_client_id] = state
    logger.info(f"Client connected: {x_client_id}")

    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        if state.replay:
            await state.replay.cleanup()
        connected_clients.pop(x_client_id, None)
        logger.info(f"Client disconnected: {x_client_id}")


def run_server(host: str = "0.0.0.0", port: int = 8000, from_recording: Path | None = None):
    global _from_recording
    _from_recording = from_recording
    uvicorn.run(app, host=host, port=port)
